### ISSUE TITLE
FileSync: Enable/Disable (SublimeText 2)

### ISSUE THREAD

**Issue by leoj3n** [bcharbonnier/SublimeFileSync#12]
Couldn't get it to work at first, not until I toggled this setting:

![fs](https://f.cloud.github.com/assets/990216/830305/e958f718-f141-11e2-9b41-a4671a902a97.png)
## Fresh Sublime Text 2 Launch

```
theme loaded
app ready
pre session restore time: 1.16854
using gpu buffer for window
using gamma: 1 (err: 0)
using gpu buffer for window
startup cache, total files: 237 cache hits: 237
startup time: 1.44324 (package setup was not run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2013-07-20 08:10:09, next run at 2013-07-20 09:10:09 or after
```
## Save File

```
Writing file /Users/leoj/wp/plugs/bootstrap-shortcodes/bootstrap_shortcodes.php with encoding UTF-8
```
## Toggle `FileSync: Enable/Disable`

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./filesync.py", line 29, in run
  File "./filesync.py", line 43, in rename_sidebar_menu
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shutil.py", line 260, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shutil.py", line 95, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/leoj/Library/Application Support/Sublime Text 2/Packages/FileSync/Side Bar.sublime-menu.disabled'
theme loaded
```
## Save File Again

```
Writing file /Users/leoj/wp/plugs/bootstrap-shortcodes/bootstrap_shortcodes.php with encoding UTF-8
[FileSync] Trying to sync '/Users/leoj/wp/plugs/bootstrap-shortcodes/bootstrap_shortcodes.php'
[FileSync] Copying...
[FileSync] /Users/leoj/wp/plugs/bootstrap-shortcodes/bootstrap_shortcodes.php has been synchronised -> /Users/leoj/wp/apps/example.com/app/plugins/bootstrap-shortcodes/bootstrap_shortcodes.php
```

Every time I restart I have to toggle Enable/Disable. ~~Also note the python console output doesn't match the README~~.

Edit: The console output matches the README when using the sidebar menu on a folder.

**Comment by eddieben** [comment]
Adding "filesync_enabled": true to the FileSync.sublime.settings - User fixed the issue for me.  FyleSync now always shows as enabled every time I close and open Sublime.
