### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by tablatronix** [bcharbonnier/SublimeFileSync#36]
Plugin randomly stops working, disable and renable via package control fixes issue.

```
Traceback (most recent call last):
  File "bin\sublimetext\sublime_plugin.py", line 256, in on_post_save
    callback.on_post_save(v)
  File "bin\sublimetext\Data\Packages\FileSync\filesync.py", line 171, in on_post_save
    sync_file(view.file_name())
  File "bin\sublimetext\Data\Packages\FileSync\filesync.py", line 234, in sync_file
    for exclusion in _settings.get("exclude_folder_names"):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jonathanbell** [comment]
+1

**Comment by migliori** [comment]
+1

**Comment by colincameron** [comment]
+1

**Comment by juandpr** [comment]
+1

**Comment by tablatronix** [comment]
Anyone figure this out yet ? I have yet to look into the code

**Comment by cheer021** [comment]
+1

**Comment by romaopedro** [comment]
+1

**Comment by wouter-muller** [comment]
+1

**Comment by twigz20** [comment]
+1

**Comment by mtr512** [comment]
What seems to have fixed this for me on Sublime Text 3 is adding an enabled line to my filesync settings file.  I added:

 "filesync_enabled": true ,

So this is what my file looks like now...

 {
   "exclude_folder_names": [".git", ".svn", ".hg"],
  "filesync_enabled": true ,
  "mappings": [
     {
      "source": "/Users/myname/clientname/jt3", //Unix style paths
      "destination": "/Volumes/Sites/dev/clientname/jt"
    }
  ]
}

Hopefully this works for you. This was driving me crazy.

**Comment by tablatronix** [comment]
Omg I will test

**Comment by wouter-muller** [comment]
Wow, i also just added that! Will check back in a few days to report if the issue is fixed...

**Comment by colincameron** [comment]
Based on @mtr512's findings, it looks like this is the same issue as #12, which claims to be fixed in #31 - an unmerged PR from 2014.

**Comment by tablatronix** [comment]
I have this in my user file, and have for awhile, I still have issues.

**Comment by mtr512** [comment]
Update, to confirm what @tablatronix said, while adding the filesync enabled line has seemed to improve the chances of filesync working for me, I have noticed occasional stoppages still. So it may improve chances of it working but doesn't solve it totally based on what I'm seeing.

**Comment by tablatronix** [comment]
Has anyone tried this pr?
https://github.com/bcharbonnier/SublimeFileSync/pull/31

**Comment by wouter-muller** [comment]
I have tried adding the filesync enabled line and also still experience occasional stoppages...
