### ISSUE TITLE
[Bug] Can not begin to work issue

### ISSUE THREAD

**Issue by Kristinita** [bcharbonnier/SublimeFileSync#37]
### Summary

I can not synchronize my folders use FileSync.
### Expected behavior

Successful synchronization my folders.
### Actual behavior

``` python
key evt: control+s
command: save
'cannot find TOC tags'
[FileSync] Trying to sync 'E:\Sublime Text 3\Data\Packages\SashaSublime\README.md'
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "E:\Sublime Text 3\sublime_plugin.py", line 473, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "filesync in E:\Sublime Text 3\Data\Installed Packages\FileSync.sublime-package", line 171, in on_post_save
  File "filesync in E:\Sublime Text 3\Data\Installed Packages\FileSync.sublime-package", line 234, in sync_file
AttributeError: 'NoneType' object has no attribute 'get'
```
### Steps to reproduce

My `User\FileSync.sublime-settings` file:

``` json
{
    "filesync_enabled": true,
    "mappings": [
        {
            "source": "E:/Sublime Text 3/Data/Packages/SashaSublime",
            "destination": "E:/SashaSublime"
        },
    ]
}

```

Paths to folders is correct. When I save my file in `E:/Sublime Text 3/Data/Packages/SashaSublime` folder I get stack trace.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Kristinita** [comment]
Incorrect format. Right:

```json
{
    "filesync_enabled": true,
    "mappings": [
        {
            "source": "E:\\Sublime Text 3\\Data/Packages\\SashaSublime",
            "destination": "E:\\SashaSublime"
        },
    ]
}
```

Thanks.
